[package]
name = "cryptography-types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
bincode = { workspace = true }

[features]
default = ["std"]
std = []